---
- name: domain_groups | Generate Domain Group List
  command: samba-tool group list
  register: _samba_domain_groups
  become: true

- name: domain_groups | Creating Domain Groups
  command: samba-tool group add {{ item['name'] }}
  become: true
  with_items: "{{ samba_domain_groups }}"
  when: item['name'] not in _samba_domain_groups['stdout']

- name: domain_groups | Managing Domain Group Members
  command: samba-tool group listmembers "{{ item['name'] }}"
  become: true
  register: _samba_domain_group_members
  with_items: "{{ samba_domain_groups }}"

