---
# tasks file for ansible-samba
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: samba_groups.yml
  when: samba_groups is defined

- include: samba_users.yml
  when: samba_users is defined

- include: create_shares.yml
  when: samba_shares is defined

- include: config_samba.yml

- include: domain_users.yml
  when: >
        samba_create_domain_users is defined and
        samba_create_domain_users
